#!/usr/bin/env python3
"""
Generate Data/Phases.lua from the shared MaNGOS phase dataset.

Source of truth: ../bgc-external/mangos_phases/phases.json
Output:          ../Data/Phases.lua

The generated file declares two tables:
    RecipeBook.recipePhases[itemId]      = phase  -- recipe item id
    RecipeBook.recipeSpellPhases[spellId] = phase  -- taught craft spell id

Lookup rule in Core.lua:GetRecipePhase() — prefer recipeSpellPhases[teaches],
fall back to recipePhases[recipeItemId], then zone-based inference.

Phase schema: MaNGOS 0 (pre-TBC Classic) is folded into phase 1, matching
RecipeBook's 1-5 UI filter.

Re-run whenever the upstream dataset changes:
    python3 tools/generate_phases.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
PHASES_JSON = os.path.normpath(
    os.path.join(REPO, "..", "bgc-external", "mangos_phases", "phases.json")
)
OUT_LUA = os.path.join(REPO, "Data", "Phases.lua")


def fold_phase(p):
    """Fold MaNGOS phase 0 (pre-TBC) into RecipeBook phase 1."""
    return 1 if p == 0 else p


def main():
    if not os.path.exists(PHASES_JSON):
        sys.exit(f"ERROR: phases.json not found at {PHASES_JSON}")

    with open(PHASES_JSON) as f:
        data = json.load(f)

    recipe_items = {int(k): fold_phase(v) for k, v in data["recipeItems"].items()}
    recipe_spells = {int(k): fold_phase(v) for k, v in data["recipeSpells"].items()}

    lines = []
    lines.append("-- RecipeBook Phase Dataset")
    lines.append("-- AUTO-GENERATED by tools/generate_phases.py — DO NOT EDIT BY HAND")
    lines.append("-- Source: bgc-external/mangos_phases/phases.json")
    lines.append("-- Derived from CMaNGOS tbc-db (2.4.3), cross-checked vs Wowhead.")
    lines.append("--")
    lines.append("-- Phase schema (RecipeBook UI filters 1-5):")
    lines.append("--   1 = TBC launch (2.0) + pre-TBC Classic recipes")
    lines.append("--   2 = SSC / Tempest Keep (2.1)")
    lines.append("--   3 = Mount Hyjal / Black Temple / 2.1 dailies")
    lines.append("--   4 = Zul'Aman (2.3)")
    lines.append("--   5 = Sunwell / Magisters' Terrace / Isle of Quel'Danas (2.4)")
    lines.append("")
    lines.append("RecipeBook = RecipeBook or {}")
    lines.append("")

    # Recipe spell phases (primary lookup)
    lines.append(f"-- Taught craft spell id -> phase ({len(recipe_spells)} entries)")
    lines.append("RecipeBook.recipeSpellPhases = {")
    for spell_id in sorted(recipe_spells):
        lines.append(f"\t[{spell_id}] = {recipe_spells[spell_id]},")
    lines.append("}")
    lines.append("")

    # Recipe item phases (fallback lookup)
    lines.append(f"-- Recipe item id -> phase ({len(recipe_items)} entries)")
    lines.append("RecipeBook.recipePhases = {")
    for item_id in sorted(recipe_items):
        lines.append(f"\t[{item_id}] = {recipe_items[item_id]},")
    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(OUT_LUA), exist_ok=True)
    with open(OUT_LUA, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {OUT_LUA}")
    print(f"  recipeSpellPhases: {len(recipe_spells)}")
    print(f"  recipePhases:      {len(recipe_items)}")


if __name__ == "__main__":
    main()
